import type { CountriesItem } from './countries.types'

export const countriesData: CountriesItem[] = [
	{ name: 'Австрия', flag: '/images/flags/austria.svg' },
	{ name: 'Азербайджан', flag: '/images/flags/azerbaijan.svg' },
	{ name: 'Армения', flag: '/images/flags/armenia.svg' },
	{ name: 'Бельгия', flag: '/images/flags/belgium.svg' },
	{ name: 'Болгария', flag: '/images/flags/bulgaria.svg' },
	{ name: 'Великобритания', flag: '/images/flags/uk.svg' },
	{ name: 'Венгрия', flag: '/images/flags/hungary.svg' },
	{ name: 'Германия', flag: '/images/flags/germany.svg' },
	{ name: 'Греция', flag: '/images/flags/greece.svg' },
	{ name: 'Грузия', flag: '/images/flags/georgia.svg' },
	{ name: 'Израиль', flag: '/images/flags/israel.svg' },
	{ name: 'Исландия', flag: '/images/flags/iceland.svg' },
	{ name: 'Испания', flag: '/images/flags/spain.svg' },
	{ name: 'Италия', flag: '/images/flags/italy.svg' },
	{ name: 'Казахстан', flag: '/images/flags/kazakhstan.svg' },
	{ name: 'Киргизия', flag: '/images/flags/kyrgyzstan.svg' },
	{ name: 'Канада', flag: '/images/flags/canada.svg' },
	{ name: 'Кипр Юг', flag: '/images/flags/cyprus.svg' },
	{ name: 'Кипр Север', flag: '/images/flags/north_cyprus.svg' },
	{ name: 'Китай', flag: '/images/flags/china.svg' },
	{ name: 'Латвия', flag: '/images/flags/latvia.svg' },
	{ name: 'Литва', flag: '/images/flags/lithuania.svg' },
	{ name: 'Молдова', flag: '/images/flags/moldova.svg' },
	{ name: 'Нидерланды', flag: '/images/flags/netherlands.svg' },
	{ name: 'Норвегия', flag: '/images/flags/norway.svg' },
	{ name: 'ОАЭ', flag: '/images/flags/uae.svg' },
	{ name: 'Польша', flag: '/images/flags/poland.svg' },
	{ name: 'Португалия', flag: '/images/flags/portugal.svg' },
	{ name: 'Словакия', flag: '/images/flags/slovakia.svg' },
	{ name: 'Сербия', flag: '/images/flags/serbia.svg' },
	{ name: 'Словения', flag: '/images/flags/slovenia.svg' },
	{ name: 'США', flag: '/images/flags/usa.svg' },
	{ name: 'Турция', flag: '/images/flags/turkey.svg' },
	{ name: 'Узбекистан', flag: '/images/flags/uzbekistan.svg' },
	{ name: 'Франция', flag: '/images/flags/france.svg' },
	{ name: 'Черногория', flag: '/images/flags/montenegro.svg' },
	{ name: 'Чехия', flag: '/images/flags/czech.svg' },
	{ name: 'Швейцария', flag: '/images/flags/switzerland.svg' },
	{ name: 'Швеция', flag: '/images/flags/sweden.svg' },
	{ name: 'Эстония', flag: '/images/flags/estonia.svg' },
	{ name: 'Южная Корея', flag: '/images/flags/south_korea.svg' }
]
